---
- hosts: all
  become: true

  tasks:
    - name: Updating apt
      apt: update_cache=yes

    - name: Install aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Installing Required Packages for Docker
      apt: name={{ item }} state=latest update_cache=yes force_apt_get=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Adding the GPG Key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Updating apt
      apt: update_cache=yes

    - name: Installing docker-ce
      apt: name=docker-ce state=latest

    - name: Installing a Python package for docker
      pip:
        name: docker

    - name: Adding the current user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Copying certs to app server
      copy:
        src: "{{ playbook_dir }}/../certs"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0400

    - name: Starting a Docker image
      docker_container:
        name: rest_api_calc_container
        image: swixel/rest_api_calc
        state: started
        container_default_behavior: compatibility
        ports:
          - "443:5000"
        volumes:
          - /home/ubuntu/certs:/certs
